const fs = require('node:fs')
const path = require('node:path')
const source = fs.readFileSync(path.join(__dirname, 'lib.cjs'), 'utf8')
for (const mode of ['check', 'preview', 'publish', 'all']) {
  const target = path.join(__dirname, 'quickadd', `permanent-${mode}.js`)
  const output = `// Generated by scripts/permanent-notes/generate.cjs\n${source}\nmodule.exports = createQuickAddModule('${mode}')\n`
  if (process.argv.includes('--check')) {
    if (fs.readFileSync(target, 'utf8') !== output) throw new Error(`Stale bundle: ${target}`)
  } else {
    fs.mkdirSync(path.dirname(target), { recursive: true })
    fs.writeFileSync(target, output)
  }
}
