// Generated by scripts/journal/generate.cjs
const CONTENT_TYPE = 'journalEntry'
const ROOT = '05-Areas/Journal/Entries/'
const schema = {
  name: 'Journal Entry',
  description: 'Journey timeline entries: only Log, Thoughts and Review from Obsidian Journal.',
  displayField: 'title',
  fields: [
    {
      id: 'noteId',
      name: 'Note ID',
      type: 'Symbol',
      required: true,
      validations: [{ unique: true }, { regexp: { pattern: '^[0-9]{14}$' } }]
    },
    { id: 'title', name: 'Title', type: 'Symbol', required: true },
    { id: 'date', name: 'Journal date', type: 'Date', required: true },
    { id: 'tags', name: 'Tags', type: 'Array', items: { type: 'Symbol' } },
    { id: 'log', name: 'Log Markdown', type: 'Text' },
    { id: 'thoughts', name: 'Thoughts Markdown', type: 'Text' },
    { id: 'review', name: 'Review Markdown', type: 'Text' },
    { id: 'linkedNoteIds', name: 'Linked Permanent card IDs', type: 'Array', items: { type: 'Symbol' } }
  ]
}
const str = (value) => (value == null ? '' : String(value).trim())
const unique = (values) => [...new Set(values)]
const entryId = (id) => `journalEntry_${id}`
const normalize = (raw) => raw.replace(/^\uFEFF/, '').replace(/\r\n?/g, '\n')

function protectCode(markdown) {
  const tokens = []
  const save = (text) => `\u0000J${tokens.push(text) - 1}\u0000`
  const lines = []
  let fence,
    block = []
  for (const line of markdown.split('\n')) {
    const match = line.match(/^ {0,3}(`{3,}|~{3,})(.*)$/)
    if (fence) {
      block.push(line)
      if (match && match[1][0] === fence[0] && match[1].length >= fence.length && !match[2].trim()) {
        lines.push(save(block.join('\n')))
        fence = null
        block = []
      }
    } else if (match) {
      fence = match[1]
      block = [line]
    } else lines.push(/^(?: {4}|\t)/.test(line) ? save(line) : line)
  }
  if (block.length) lines.push(save(block.join('\n')))
  return {
    text: lines.join('\n').replace(/(`+)([^]*?)\1(?!`)/g, save),
    restore: (text) => text.replace(/\u0000J(\d+)\u0000/g, (_, i) => tokens[Number(i)])
  }
}

function cleanSection(lines) {
  const root = { level: 0, children: [] }
  const stack = [root]
  let prompt = false
  for (let line of lines) {
    if (/^\s*>\s*\[!tip\][+-]?\s+Writing prompt\s*$/i.test(line)) {
      prompt = true
      continue
    }
    if (prompt && /^\s*>/.test(line)) continue
    prompt = false
    if (/^\s*(?:[-+*]|\d+\.)\s*(?:\[[ x-]\])?\s*$/.test(line)) line = ''
    const heading = line.match(/^ {0,3}(#{3,6})\s+/)
    if (heading) {
      while (stack.at(-1).level >= heading[1].length) stack.pop()
      const node = { level: heading[1].length, heading: line, children: [] }
      stack.at(-1).children.push(node)
      stack.push(node)
    } else stack.at(-1).children.push(line)
  }
  const render = (node) => {
    const body = node.children
      .map((c) => (typeof c === 'string' ? c : render(c)))
      .join('\n')
      .trim()
    return !body || /^(?:\s|---|\*\*\*)*$/.test(body) ? '' : `${node.heading ? node.heading + '\n\n' : ''}${body}`
  }
  return render(root)
}

function parseJournal(file, raw, parseYaml) {
  if (!file?.path?.startsWith(ROOT) || file.extension !== 'md') throw new Error(`Select a Markdown note under ${ROOT}`)
  raw = normalize(raw)
  const front = raw.match(/^---\n([^]*?)\n---(?:\n|$)/)
  if (!front) throw new Error(`${file.path}: frontmatter required`)
  const fm = parseYaml(front[1]) || {}
  if (fm.type !== 'journal') throw new Error(`${file.path}: type must be journal`)
  const id = str(fm.id)
  if (!/^\d{14}$/.test(id)) throw new Error(`${file.path}: id must be a stable 14-digit timestamp`)
  if (fm.contentful_note_id && str(fm.contentful_note_id) !== id) throw new Error(`${file.path}: synced id changed`)
  if (fm.contentful_entry_id && fm.contentful_entry_id !== entryId(id))
    throw new Error(`${file.path}: entry identity mismatch`)
  if (fm.contentful_content_type && fm.contentful_content_type !== CONTENT_TYPE)
    throw new Error(`${file.path}: content type mismatch`)
  const date = fm.date instanceof Date ? fm.date.toISOString().slice(0, 10) : str(fm.date)
  if (
    !/^\d{4}-\d{2}-\d{2}$/.test(date) ||
    !Number.isFinite(Date.parse(`${date}T00:00:00Z`)) ||
    new Date(`${date}T00:00:00Z`).toISOString().slice(0, 10) !== date
  )
    throw new Error(`${file.path}: date must be a real YYYY-MM-DD date`)
  const protectedBody = protectCode(raw.slice(front[0].length))
  const body = protectedBody.text
    .replace(/<!--[^]*?(?:-->|$)|%%[^]*?(?:%%|$)/g, '')
    .replace(
      /^([^\n\u0000]+)\n(={3,}|-{3,})\s*$/gm,
      (_, title, underline) => `${underline[0] === '=' ? '#' : '##'} ${title.trim()}`
    )
  const title = str(fm.title) || body.match(/^#\s+(.+?)\s*#*\s*$/m)?.[1] || file.basename
  const sections = { log: [], thoughts: [], review: [] }
  let section = null
  for (const line of body.split('\n')) {
    const heading = line.match(/^ {0,3}(#{1,2})\s+(.+?)\s*#*\s*$/)
    if (heading) {
      const key = heading[2].toLowerCase()
      section = heading[1].length === 2 && Object.hasOwn(sections, key) ? key : null
    } else if (section) sections[section].push(line)
  }
  const fields = {
    noteId: id,
    title,
    date: `${date}T00:00:00.000Z`,
    tags: unique((Array.isArray(fm.tags) ? fm.tags : fm.tags ? [fm.tags] : []).map(str).filter(Boolean))
  }
  for (const [key, lines] of Object.entries(sections)) fields[key] = protectedBody.restore(cleanSection(lines))
  return { id, file, raw, fm, fields, empty: !fields.log && !fields.thoughts && !fields.review }
}

function convertLinks(markdown, file, app) {
  const code = protectCode(markdown)
  const linked = new Set(),
    warnings = new Set()
  const label = (s) => s.replace(/[\\[\]]/g, '\\$&')
  const convert = (target, display, image, whole) => {
    if (/^(?:https?:|mailto:|tel:|\/\/)/i.test(target)) return whole
    if (target.startsWith('#') && !image) return whole
    if (/^[a-z][a-z\d+.-]*:/i.test(target)) throw new Error(`${file.path}: unsupported URL ${target}`)
    if (image) throw new Error(`${file.path}: upload local images/embeds before publishing: ${target}`)
    try {
      target = decodeURIComponent(target)
    } catch {
      throw new Error(`${file.path}: malformed link ${target}`)
    }
    const [linkpath, ...anchor] = target.split('#')
    let id = linkpath.match(/^\/cards\/(\d{14})$/)?.[1]
    if (!id) {
      const dest = app.metadataCache.getFirstLinkpathDest(linkpath.replace(/\.md$/i, ''), file.path)
      const fm = dest && app.metadataCache.getFileCache(dest)?.frontmatter
      if (
        dest?.path.startsWith('02-Zettelkasten/Permanent/') &&
        fm?.type === 'permanent-note' &&
        /^\d{14}$/.test(str(fm.id))
      )
        id = str(fm.id)
    }
    if (!id) {
      warnings.add(`Local link rendered as text: ${target}`)
      return label(display || linkpath.split('/').pop())
    }
    if (anchor.length) warnings.add(`Obsidian anchor omitted: ${target}`)
    linked.add(id)
    return `[${label(display || linkpath.split('/').pop())}](/cards/${id})`
  }
  let text = code.text.replace(
    /(?:https?:\/\/)[^\s<>]+|\\[^]|(!?)\[\[([^\]\n]+)\]\]|(!?)\[([^\]\n]*)\]\(\s*(<[^>\n]+>|(?:[^\s()]|\([^()]*\))+)(?:\s+"[^"\n]*")?\s*\)/g,
    (whole, wi, wiki, mi, ml, mt) => {
      if (whole.startsWith('\\') || /^https?:\/\//i.test(whole)) return whole
      if (wiki !== undefined) {
        const [target, ...labels] = wiki.split('|')
        return convert(target, labels.join('|'), !!wi, whole)
      }
      return convert(mt.replace(/^<|>$/g, ''), ml, !!mi, whole)
    }
  )
  // Reference links must be explicitly converted to inline links so no private destination slips through.
  for (const match of text.matchAll(/^ {0,3}\[([^\]\n]+)\]:\s*(<[^>\n]+>|\S+).*$/gm)) {
    if (!/^(?:https?:|mailto:|tel:|\/\/)/i.test(match[2]))
      throw new Error(`${file.path}: convert local reference link [${match[1]}] to an inline link before publishing`)
  }
  if (/(?<![\\!])\[\[/.test(text)) throw new Error(`${file.path}: unsupported wikilink syntax`)
  return { markdown: code.restore(text), linked: [...linked], warnings: [...warnings] }
}

async function buildPlan(app, parseYaml, files) {
  const ids = new Map()
  for (const f of app.vault.getMarkdownFiles().filter((f) => f.path.startsWith(ROOT))) {
    const raw = normalize(await app.vault.read(f))
    const fm = parseYaml(raw.match(/^---\n([^]*?)\n---(?:\n|$)/)?.[1] || '') || {}
    const id = str(fm.id)
    if (id && ids.has(id)) throw new Error(`Duplicate Journal id ${id}: ${ids.get(id)}, ${f.path}`)
    if (id) ids.set(id, f.path)
  }
  const notes = [],
    skipped = [],
    warnings = []
  for (const file of files) {
    const note = parseJournal(file, await app.vault.read(file), parseYaml)
    if (note.empty) {
      skipped.push(file.path)
      continue
    }
    const linked = []
    for (const key of ['log', 'thoughts', 'review']) {
      const result = convertLinks(note.fields[key], file, app)
      note.fields[key] = result.markdown
      linked.push(...result.linked)
      warnings.push(...result.warnings)
    }
    note.fields.linkedNoteIds = unique(linked)
    notes.push(note)
  }
  return { notes, skipped, warnings: unique(warnings) }
}

function readSettings(settings = {}, environment = process.env) {
  const defaults = {
    spaceId: '',
    environmentId: 'master',
    managementToken: '',
    locale: 'en-US',
    cmaBaseUrl: 'https://api.contentful.com',
    revalidateUrl: '',
    revalidateSecret: ''
  }
  const env = {
    spaceId: 'CONTENTFUL_SPACE_ID',
    environmentId: 'CONTENTFUL_ENVIRONMENT_ID',
    managementToken: 'CONTENTFUL_MANAGEMENT_TOKEN',
    locale: 'CONTENTFUL_LOCALE',
    cmaBaseUrl: 'CONTENTFUL_CMA_BASE_URL',
    revalidateUrl: 'CONTENTFUL_REVALIDATE_URL',
    revalidateSecret: 'NEXT_REVALIDATE_SECRET'
  }
  const config = {}
  for (const key of Object.keys(defaults)) {
    let value = str(settings[key]) || str(environment[env[key]]) || defaults[key]
    if (value.startsWith('env:')) {
      value = str(environment[value.slice(4)])
      if (!value) throw new Error(`Missing environment variable for ${key}`)
    }
    config[key] = value
  }
  for (const key of ['spaceId', 'environmentId', 'managementToken', 'locale'])
    if (!config[key]) throw new Error(`Missing ${key}`)
  const url = new URL(config.cmaBaseUrl)
  if (
    !['https://api.contentful.com', 'https://api.eu.contentful.com'].includes(url.origin) ||
    url.pathname !== '/' ||
    url.search ||
    url.hash ||
    url.username ||
    url.password
  )
    throw new Error('Use an official Contentful CMA HTTPS URL')
  config.cmaBaseUrl = url.origin
  if (config.revalidateUrl) {
    const url = new URL(config.revalidateUrl)
    if (!config.revalidateSecret) throw new Error('Revalidation secret is required with revalidateUrl')
    if (
      url.protocol !== 'https:' &&
      !(url.protocol === 'http:' && ['localhost', '127.0.0.1', '[::1]'].includes(url.hostname))
    )
      throw new Error('Use HTTPS for revalidation (HTTP localhost is supported)')
  }
  return config
}

function createClient(config, fetcher = fetch, wait = (ms) => new Promise((r) => setTimeout(r, ms))) {
  const base = `${config.cmaBaseUrl}/spaces/${encodeURIComponent(config.spaceId)}/environments/${encodeURIComponent(config.environmentId)}`
  return {
    async request(method, path, body, version) {
      for (let attempt = 0; attempt < 4; attempt++) {
        const headers = {
          Authorization: `Bearer ${config.managementToken}`,
          'Content-Type': 'application/vnd.contentful.management.v1+json'
        }
        if (version !== undefined) headers['X-Contentful-Version'] = String(version)
        if (method === 'PUT' && /^\/entries\/[^/]+$/.test(path)) headers['X-Contentful-Content-Type'] = CONTENT_TYPE
        const response = await fetcher(base + path, {
          method,
          headers,
          body: body === undefined ? undefined : JSON.stringify(body),
          signal: AbortSignal.timeout(30000)
        })
        if (response.status === 429 && attempt < 3) {
          const delay = Number(response.headers.get('x-contentful-ratelimit-reset')) || 1
          await wait(Math.min(30000, Math.max(1000, delay * 1000)))
          continue
        }
        if (method === 'GET' && response.status === 404) return null
        if (!response.ok) throw new Error(`Contentful ${method} ${path}: HTTP ${response.status}`)
        return response.json()
      }
    }
  }
}

function assertSchema(model) {
  if (!model?.sys?.publishedVersion)
    throw new Error('Journal model is missing; run scripts/journal/setup.cjs --apply first')
  for (const desired of schema.fields) {
    const field = model.fields.find((f) => f.id === desired.id)
    if (
      !field ||
      field.type !== desired.type ||
      field.disabled ||
      field.omitted ||
      (field.type === 'Array' && field.items?.type !== 'Symbol')
    )
      throw new Error(`Journal model mismatch: ${desired.id}`)
  }
  if (model.fields.some((f) => f.required && !schema.fields.some((d) => d.id === f.id)))
    throw new Error('Journal model has an unknown required field')
}

async function setup(client) {
  const path = `/content_types/${CONTENT_TYPE}`
  const model = await client.request('GET', path)
  if (model)
    for (const field of model.fields) {
      const desired = schema.fields.find((d) => d.id === field.id)
      if (
        !desired ||
        desired.type !== field.type ||
        field.localized ||
        (field.type === 'Array' && field.items?.type !== desired.items.type)
      )
        throw new Error(`Manual model migration required: ${field.id}`)
    }
  const updated = await client.request('PUT', path, schema, model?.sys.version)
  return client.request('PUT', `${path}/published`, undefined, updated.sys.version)
}

async function syncPlan(plan, client, config, mode, writeState = async () => {}) {
  if (!['preview', 'publish'].includes(mode)) throw new Error('Invalid sync mode')
  const result = { mode, synced: [], published: [], unchanged: [], skipped: plan.skipped, warnings: plan.warnings }
  if (!plan.notes.length) return result
  try {
    const model = await client.request('GET', `/content_types/${CONTENT_TYPE}`)
    assertSchema(model)
    const locales = await client.request('GET', '/locales')
    if (!locales.items.some((l) => l.code === config.locale)) throw new Error(`Unknown locale: ${config.locale}`)
    const defaultLocale = locales.items.find((l) => l.default)?.code
    if (defaultLocale && defaultLocale !== config.locale && model.fields.some((f) => !f.localized))
      throw new Error(`Use model default locale: ${defaultLocale}`)
    for (const id of unique(plan.notes.flatMap((n) => n.fields.linkedNoteIds))) {
      const card = await client.request('GET', `/entries/permanentNote_${id}`)
      if (
        !card?.sys?.publishedVersion ||
        card.sys.contentType?.sys?.id !== 'permanentNote' ||
        Object.values(card.fields?.noteId || {}).some((value) => value !== id)
      )
        throw new Error(`Publish Permanent card ${id} first`)
    }
    const records = []
    for (const note of plan.notes) {
      const path = `/entries/${entryId(note.id)}`
      const current = await client.request('GET', path)
      if (
        current &&
        (current.sys.contentType?.sys?.id !== CONTENT_TYPE ||
          Object.values(current.fields?.noteId || {}).some((value) => value !== note.id))
      )
        throw new Error(`Remote identity mismatch: ${note.id}`)
      if (current?.sys.archivedVersion) throw new Error(`Entry is archived: ${note.id}`)
      const fields = { ...current?.fields }
      for (const [key, value] of Object.entries(note.fields)) fields[key] = { ...fields[key], [config.locale]: value }
      const changed =
        !current ||
        Object.entries(note.fields).some(
          ([key, value]) => JSON.stringify(current.fields[key]?.[config.locale]) !== JSON.stringify(value)
        )
      records.push({ note, path, current, fields, changed })
    }
    for (const record of records) {
      let current = record.current
      if (record.changed)
        current = await client.request('PUT', record.path, { fields: record.fields }, current?.sys.version)
      else result.unchanged.push(record.note.id)
      result.synced.push(record.note.id)
      if (mode === 'publish') {
        if (!current.sys.publishedVersion || current.sys.version !== current.sys.publishedVersion + 1)
          await client.request('PUT', `${record.path}/published`, undefined, current.sys.version)
        result.published.push(record.note.id)
      }
      await writeState(record.note, mode)
    }
    return result
  } catch (error) {
    error.result = result
    error.message += `; synced ${result.synced.length}, published ${result.published.length}/${plan.notes.length}. Rerun to resume.`
    throw error
  }
}

async function revalidate(config, result, fetcher = fetch) {
  if (!config.revalidateUrl || !result.published.length) return false
  const response = await fetcher(config.revalidateUrl, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'x-revalidate-secret': config.revalidateSecret },
    body: JSON.stringify({ contentTypeId: CONTENT_TYPE }),
    signal: AbortSignal.timeout(30000)
  })
  if (!response.ok || (await response.json()).revalidated !== true)
    throw new Error(`Journey refresh failed: HTTP ${response.status}`)
  return true
}

const running = (globalThis[Symbol.for('journal-publisher.running')] ||= new WeakSet())
function createQuickAddModule(mode) {
  const names = {
    check: 'Journal Check Current',
    preview: 'Journal Preview Current',
    publish: 'Journal Publish Current',
    all: 'Journal Publish All'
  }
  if (!names[mode]) throw new Error('Invalid Journal mode')
  const options = Object.fromEntries(
    Object.entries({
      spaceId: '',
      environmentId: 'master',
      managementToken: 'env:CONTENTFUL_MANAGEMENT_TOKEN',
      locale: 'en-US',
      cmaBaseUrl: 'https://api.contentful.com',
      revalidateUrl: '',
      revalidateSecret: ''
    }).map(([key, value]) => [
      key,
      {
        type: 'text',
        name: key,
        defaultValue: value,
        description: 'Supports env:VARIABLE_NAME. Publishes Log, Thoughts and Review only.'
      }
    ])
  )
  return {
    settings: { name: names[mode], author: 'Codex', options },
    entry: async ({ app, obsidian }, settings = {}) => {
      if (running.has(app)) throw new Error('A Journal sync is already running')
      running.add(app)
      let config
      try {
        const files =
          mode === 'all'
            ? app.vault.getMarkdownFiles().filter((f) => f.path.startsWith(ROOT))
            : [app.workspace.getActiveFile()]
        if (!files[0]) throw new Error(`Open a Journal note under ${ROOT}`)
        const plan = await buildPlan(app, obsidian.parseYaml, files)
        if (mode === 'check' || !plan.notes.length) {
          new obsidian.Notice(
            `Journal: ${plan.notes.length} ready; ${plan.skipped.length} empty notes skipped.\nPublishes Log, Thoughts and Review only.\n${plan.notes.map((n) => n.fields.title).join('\n')}\n${plan.warnings.join('\n')}`,
            15000
          )
          return { fields: plan.notes.map((n) => n.fields), skipped: plan.skipped, warnings: plan.warnings }
        }
        config = readSettings(settings)
        const result = await syncPlan(
          plan,
          createClient(config),
          config,
          mode === 'preview' ? 'preview' : 'publish',
          async (note, mode) => {
            if (normalize(await app.vault.read(note.file)) !== note.raw)
              throw new Error(`${note.file.path}: edited during sync; rerun with the latest content`)
            await app.fileManager.processFrontMatter(note.file, (fm) => {
              if (str(fm.id) !== note.id) throw new Error(`${note.file.path}: id changed during sync`)
              Object.assign(fm, {
                contentful_content_type: CONTENT_TYPE,
                contentful_entry_id: entryId(note.id),
                contentful_note_id: note.id,
                contentful_locale: config.locale,
                contentful_last_mode: mode === 'publish' ? 'published' : 'preview',
                contentful_last_synced_at: new Date().toISOString()
              })
              if (mode === 'publish') fm.contentful_last_published_at = new Date().toISOString()
            })
          }
        )
        try {
          result.revalidated = await revalidate(config, result)
        } catch (error) {
          result.revalidateError = error.message
        }
        new obsidian.Notice(
          `Journal ${result.mode}: ${result.synced.length}; skipped ${result.skipped.length}.\n${result.warnings.join('\n')}\n${result.revalidateError || ''}`,
          15000
        )
        return result
      } catch (error) {
        if (config && error.result?.published.length)
          try {
            await revalidate(config, error.result)
          } catch (refreshError) {
            error.message += `; ${refreshError.message}`
          }
        new obsidian.Notice(`Journal sync failed: ${error.message}`, 15000)
        throw error
      } finally {
        running.delete(app)
      }
    }
  }
}

module.exports = {
  CONTENT_TYPE,
  ROOT,
  schema,
  parseJournal,
  buildPlan,
  readSettings,
  createClient,
  syncPlan,
  setup,
  revalidate,
  createQuickAddModule
}

module.exports = createQuickAddModule('preview')
