const fs = require('node:fs')
const path = require('node:path')
const prettier = require('prettier')
const schema = require('./schema.json')
const source = fs
  .readFileSync(path.join(__dirname, 'lib.cjs'), 'utf8')
  .replace("require('./schema.json')", JSON.stringify(schema))
async function generate() {
  const config = await prettier.resolveConfig(__filename)
  for (const mode of ['check', 'preview', 'publish', 'all']) {
    const target = path.join(__dirname, 'quickadd', `journal-${mode}.js`)
    const output = await prettier.format(
      `// Generated by scripts/journal/generate.cjs\n${source}\nmodule.exports = createQuickAddModule('${mode}')\n`,
      { ...config, parser: 'babel' }
    )
    if (process.argv.includes('--check')) {
      if (fs.readFileSync(target, 'utf8') !== output) throw new Error(`Stale Journal bundle: ${target}`)
    } else {
      fs.mkdirSync(path.dirname(target), { recursive: true })
      fs.writeFileSync(target, output)
    }
  }
}
generate().catch((error) => {
  console.error(error.message)
  process.exitCode = 1
})
