// Generated by scripts/permanent-notes/generate.cjs
// Independent Permanent Note publisher. No blog scripts or content types are loaded.
const CONTENT_TYPE = 'permanentNote'
const ROOT = '02-Zettelkasten/Permanent/'
const entryId = (id) => `permanentNote_${id}`
const string = (value) => (value == null ? '' : String(value).trim())
const strings = (value) => [
  ...new Set((Array.isArray(value) ? value : value ? [value] : []).map(string).filter(Boolean))
]

function noteId(value) {
  const id = string(value)
  if (!/^\d{14}$/.test(id)) throw new Error(`Invalid permanent note ID: ${id}`)
  return id
}

// Protect code and comments before recognizing sections or Markdown links.
function protect(markdown) {
  const tokens = []
  const save = (value) => `\u0000P${tokens.push(value) - 1}\u0000`
  let fence = null
  let block = []
  const lines = []
  for (const line of markdown.split('\n')) {
    const match = line.match(/^ {0,3}(`{3,}|~{3,})(.*)$/)
    if (fence) {
      block.push(line)
      if (match && match[1][0] === fence[0] && match[1].length >= fence.length && !match[2].trim()) {
        lines.push(save(block.join('\n')))
        fence = null
        block = []
      }
    } else if (match) {
      fence = match[1]
      block = [line]
    } else lines.push(/^(?: {4}|\t)/.test(line) ? save(line) : line)
  }
  if (block.length) lines.push(save(block.join('\n')))
  const text = lines.join('\n').replace(/<!--[^]*?-->|%%[^]*?%%|(`+)([^]*?)\1(?!`)/g, save)
  return { text, restore: (text) => text.replace(/\u0000P(\d+)\u0000/g, (_, n) => tokens[Number(n)]) }
}

function parseNote(file, raw, parseYaml) {
  raw = raw.replace(/^\uFEFF/, '').replace(/\r\n?/g, '\n')
  const match = raw.match(/^---\n([^]*?)\n---(?:\n|$)/)
  if (!match) throw new Error(`${file.path}: frontmatter is required`)
  const fm = parseYaml(match[1]) || {}
  if (fm.type !== 'permanent-note') throw new Error(`${file.path}: type must be permanent-note`)
  const id = noteId(fm.id)
  if (fm.contentful_note_id && string(fm.contentful_note_id) !== id) throw new Error(`${file.path}: synced ID changed`)
  if (fm.contentful_entry_id && fm.contentful_entry_id !== entryId(id))
    throw new Error(`${file.path}: entry ID mismatch`)
  if (fm.contentful_content_type && fm.contentful_content_type !== CONTENT_TYPE)
    throw new Error(`${file.path}: content type mismatch`)
  const protectedBody = protect(raw.slice(match[0].length))
  let text = protectedBody.text
  const heading = text.match(/^#\s+(.+?)\s*#*\s*$/m)
  const title = string(fm.title || heading?.[1])
  if (!title) throw new Error(`${file.path}: Chinese title is required`)
  if (heading) text = text.replace(heading[0], '')
  const parts = { bodyZh: [], bodyEn: [], sources: [] }
  let section = 'bodyZh'
  for (const line of text.split('\n')) {
    if (/^##\s+English\s*#*\s*$/i.test(line)) section = 'bodyEn'
    else if (/^##\s+(?:来源|Sources)\s*#*\s*$/i.test(line)) section = 'sources'
    else parts[section].push(line)
  }
  const sections = Object.fromEntries(
    Object.entries(parts).map(([key, lines]) => [key, protectedBody.restore(lines.join('\n')).trim()])
  )
  if (!sections.bodyZh) throw new Error(`${file.path}: Chinese body is required`)
  return {
    file,
    raw,
    fm,
    id,
    title,
    titleEn: string(fm.english_title),
    tags: strings(fm.tags),
    aliases: strings(fm.aliases),
    ...sections
  }
}

function convertLinks(markdown, note, index, app, source = false) {
  const code = protect(markdown)
  const dependencies = new Set()
  const warnings = new Set()
  const label = (s) => s.replace(/[\\[\]]/g, '\\$&')
  function convert(target, display, image, whole) {
    if (/^(?:https?:|mailto:|tel:|\/\/)/i.test(target)) return whole
    if (/^[a-z][a-z\d+.-]*:/i.test(target)) throw new Error(`${note.file.path}: unsupported URL scheme in ${target}`)
    if (target.startsWith('#') && !image) return whole
    if (image) throw new Error(`${note.file.path}: upload local image/embed first: ${target}`)
    try {
      target = decodeURIComponent(target)
    } catch {
      throw new Error(`${note.file.path}: malformed link ${target}`)
    }
    const [path, ...fragment] = target.split('#')
    const published = path.match(/^\/cards\/(\d{14})$/)
    let found
    if (published) found = index.byId.get(published[1])
    else {
      const resolved = app.metadataCache.getFirstLinkpathDest(path.replace(/\.md$/i, ''), note.file.path)
      if (resolved) found = index.byPath.get(resolved.path)
      else {
        const matches = index.notes.filter(
          (n) =>
            n.aliases.includes(path) ||
            n.file.basename === path.replace(/\.md$/i, '') ||
            n.file.path.replace(/\.md$/i, '') === path.replace(/\.md$/i, '')
        )
        if (matches.length > 1) throw new Error(`${note.file.path}: ambiguous link ${target}`)
        found = matches[0]
      }
    }
    if (!found) {
      if (!source) throw new Error(`${note.file.path}: missing or non-Permanent link ${target}`)
      warnings.add(`Local source rendered as text: ${target}`)
      return label(display || path.split('/').pop())
    }
    dependencies.add(found.id)
    // The website has no Obsidian block/heading anchors; link to the card explicitly.
    if (fragment.length) warnings.add(`Linked to whole card; Obsidian anchor omitted: ${target}`)
    return `[${label(display || found.title)}](/cards/${found.id})`
  }
  // Inline wiki and Markdown links, including balanced parentheses in destinations.
  const pattern =
    /(?:https?:\/\/)[^\s<>]+|\\[^]|(!?)\[\[([^\]\n]+)\]\]|(!?)\[([^\]\n]*)\]\(\s*(<[^>\n]+>|(?:[^\s()]|\([^()]*\))+)(?:\s+"[^"\n]*")?\s*\)/g
  let text = code.text.replace(pattern, (whole, wi, wiki, mi, ml, mt) => {
    if (whole.startsWith('\\') || /^https?:\/\//.test(whole)) return whole
    if (wiki !== undefined) {
      const [target, ...display] = wiki.split('|')
      return convert(target, display.join('|'), Boolean(wi), whole)
    }
    return convert(mt.replace(/^<|>$/g, ''), ml, Boolean(mi), whole)
  })
  // Reference definitions are normalized once; usages keep their original display text.
  const usages = text.replace(/^ {0,3}\[[^\]\n]+\]:.*$/gm, '')
  text = text.replace(/^( {0,3}\[[^\]\n]+\]:\s*)(<[^>\n]+>|\S+)(.*)$/gm, (whole, prefix, target, suffix) => {
    const key = prefix
      .match(/\[([^\]]+)\]/)[1]
      .trim()
      .replace(/\s+/g, ' ')
      .toLowerCase()
    const used = [...usages.matchAll(/(!?)\[([^\]\n]+)\](?:\[([^\]\n]*)\])?(?![\[(])/g)].filter(
      (m) => (m[3] || m[2]).trim().replace(/\s+/g, ' ').toLowerCase() === key
    )
    if (!used.length) return whole
    const converted = convert(
      target.replace(/^<|>$/g, ''),
      'reference',
      used.some((m) => m[1]),
      whole
    )
    if (converted === whole) return whole
    const url = converted.match(/^\[reference\]\((.+)\)$/)?.[1]
    if (!url) throw new Error(`${note.file.path}: use an inline link for local source ${target}`)
    return `${prefix}${url}${suffix}`
  })
  if (/(?<![\\!])\[\[[^\n]+/.test(text)) throw new Error(`${note.file.path}: unsupported wikilink syntax`)
  return { markdown: code.restore(text), dependencies: [...dependencies], warnings: [...warnings] }
}

async function buildPlan(app, parseYaml, roots) {
  const notes = []
  for (const file of app.vault.getMarkdownFiles().filter((f) => f.path.startsWith(ROOT))) {
    notes.push(parseNote(file, await app.vault.read(file), parseYaml))
  }
  const index = { notes, byId: new Map(), byPath: new Map() }
  for (const n of notes) {
    if (index.byId.has(n.id))
      throw new Error(`Duplicate note ID ${n.id}: ${index.byId.get(n.id).file.path}, ${n.file.path}`)
    index.byId.set(n.id, n)
    index.byPath.set(n.file.path, n)
  }
  const selected = new Map()
  const order = []
  function visit(note) {
    if (selected.has(note.id)) return
    const zh = convertLinks(note.bodyZh, note, index, app)
    const en = convertLinks(note.bodyEn, note, index, app)
    const sources = convertLinks(note.sources, note, index, app, true)
    const dependencies = strings([...zh.dependencies, ...en.dependencies, ...sources.dependencies]).filter(
      (id) => id !== note.id
    )
    const fields = {
      noteId: note.id,
      title: note.title,
      titleEn: note.titleEn,
      tags: note.tags,
      aliases: note.aliases,
      bodyZh: zh.markdown,
      bodyEn: en.markdown,
      sources: sources.markdown,
      linkedNoteIds: strings([...zh.dependencies, ...en.dependencies]).filter((id) => id !== note.id)
    }
    const warnings = [...zh.warnings, ...en.warnings, ...sources.warnings]
    if (!note.titleEn) warnings.push(`${note.file.path}: english_title absent; website falls back to Chinese title`)
    selected.set(note.id, { ...note, fields, dependencies, warnings })
    for (const id of dependencies) visit(index.byId.get(id))
    order.push(note.id)
  }
  for (const file of roots) {
    const note = index.byPath.get(file?.path)
    if (!note) throw new Error(`Select a note under ${ROOT}`)
    visit(note)
  }
  return { notes: order.map((id) => selected.get(id)), warnings: [...selected.values()].flatMap((n) => n.warnings) }
}

function readSettings(settings = {}, environment = process.env, validateRefresh = true) {
  const defaults = { cmaBaseUrl: 'https://api.contentful.com', environmentId: 'master', locale: 'en-US' }
  const envs = {
    spaceId: 'CONTENTFUL_SPACE_ID',
    environmentId: 'CONTENTFUL_ENVIRONMENT_ID',
    managementToken: 'CONTENTFUL_MANAGEMENT_TOKEN',
    locale: 'CONTENTFUL_LOCALE',
    revalidateUrl: 'CONTENTFUL_REVALIDATE_URL',
    revalidateSecret: 'NEXT_REVALIDATE_SECRET',
    cmaBaseUrl: 'CONTENTFUL_CMA_BASE_URL'
  }
  const config = {}
  for (const [key, env] of Object.entries(envs)) {
    let value = string(settings[key]) || string(environment[env]) || defaults[key] || ''
    if (value.startsWith('env:')) {
      value = string(environment[value.slice(4)])
      if (!value) throw new Error(`Missing environment variable for ${key}`)
    }
    config[key] = value
  }
  for (const key of ['spaceId', 'environmentId', 'managementToken', 'locale'])
    if (!config[key]) throw new Error(`Missing ${key}`)
  const url = new URL(config.cmaBaseUrl)
  if (
    url.protocol !== 'https:' ||
    !['api.contentful.com', 'api.eu.contentful.com'].includes(url.hostname) ||
    url.pathname !== '/' ||
    url.search ||
    url.hash ||
    url.username ||
    url.password
  )
    throw new Error('CMA URL must be an official Contentful HTTPS endpoint')
  config.cmaBaseUrl = url.origin
  if (validateRefresh && config.revalidateUrl && !config.revalidateSecret)
    throw new Error('Set both revalidateUrl and revalidateSecret, or leave both empty')
  if (validateRefresh && config.revalidateUrl) {
    const refreshUrl = new URL(config.revalidateUrl)
    if (
      refreshUrl.protocol !== 'https:' &&
      !(refreshUrl.protocol === 'http:' && ['localhost', '127.0.0.1', '[::1]'].includes(refreshUrl.hostname))
    )
      throw new Error('Revalidation URL must use HTTPS, or HTTP on localhost')
  }
  return config
}

function createClient(config, fetcher = fetch, wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms))) {
  const base = `${config.cmaBaseUrl}/spaces/${encodeURIComponent(config.spaceId)}/environments/${encodeURIComponent(config.environmentId)}`
  return {
    async request(method, path, body, version) {
      for (let attempt = 0; attempt < 4; attempt++) {
        const headers = {
          Authorization: `Bearer ${config.managementToken}`,
          'Content-Type': 'application/vnd.contentful.management.v1+json'
        }
        if (version !== undefined) headers['X-Contentful-Version'] = String(version)
        if (method === 'PUT' && /^\/entries\/[^/]+$/.test(path)) headers['X-Contentful-Content-Type'] = CONTENT_TYPE
        const response = await fetcher(base + path, {
          method,
          headers,
          body: body === undefined ? undefined : JSON.stringify(body),
          signal: AbortSignal.timeout(30000)
        })
        if (response.status === 429 && attempt < 3) {
          const seconds = Number(response.headers.get('x-contentful-ratelimit-reset') || 1)
          await wait(Math.min(30000, Math.max(1000, Number.isFinite(seconds) ? seconds * 1000 : 1000)))
          continue
        }
        if (method === 'GET' && response.status === 404) return null
        if (!response.ok) throw new Error(`Contentful ${method} ${path}: HTTP ${response.status}`)
        return response.json()
      }
    }
  }
}

function assertSchema(model) {
  const types = {
    noteId: 'Symbol',
    title: 'Symbol',
    titleEn: 'Symbol',
    tags: 'Array',
    aliases: 'Array',
    bodyZh: 'Text',
    bodyEn: 'Text',
    sources: 'Text',
    linkedNoteIds: 'Array'
  }
  if (!model?.sys?.publishedVersion) throw new Error('Publish the Permanent Note model with setup.cjs first')
  for (const [id, type] of Object.entries(types)) {
    const field = model.fields.find((f) => f.id === id)
    if (
      !field ||
      field.type !== type ||
      field.disabled ||
      field.omitted ||
      (type === 'Array' && field.items?.type !== 'Symbol')
    )
      throw new Error(`Permanent Note model mismatch: ${id}`)
  }
  for (const field of model.fields)
    if (field.required && !types[field.id]) throw new Error(`Unexpected required field: ${field.id}`)
}

async function syncPlan(plan, client, config, mode, writeState = async () => {}) {
  if (!['preview', 'publish'].includes(mode)) throw new Error('Invalid sync mode')
  const result = { mode, synced: [], published: [], unchanged: [], warnings: plan.warnings }
  try {
    const model = await client.request('GET', `/content_types/${CONTENT_TYPE}`)
    assertSchema(model)
    const locales = await client.request('GET', '/locales')
    if (!locales.items.some((l) => l.code === config.locale))
      throw new Error(`Unknown Contentful locale: ${config.locale}`)
    const defaultLocale = locales.items.find((l) => l.default)?.code
    if (defaultLocale && defaultLocale !== config.locale && model.fields.some((f) => !f.localized))
      throw new Error(`Non-localized model fields require the default locale: ${defaultLocale}`)
    // Read and check every remote identity before making any writes.
    const records = []
    for (const note of plan.notes) {
      const path = `/entries/${entryId(note.id)}`
      const existing = await client.request('GET', path)
      if (
        existing &&
        (existing.sys.contentType?.sys?.id !== CONTENT_TYPE ||
          Object.values(existing.fields?.noteId || {}).some((id) => id !== note.id))
      )
        throw new Error(`Remote identity mismatch: ${note.id}`)
      if (existing?.sys.archivedVersion) throw new Error(`Entry is archived: ${note.id}`)
      const fields = { ...existing?.fields }
      for (const [key, value] of Object.entries(note.fields)) fields[key] = { ...fields[key], [config.locale]: value }
      const changed =
        !existing ||
        Object.entries(note.fields).some(
          ([key, value]) => JSON.stringify(existing.fields[key]?.[config.locale]) !== JSON.stringify(value)
        )
      records.push({ note, path, entry: existing, fields, changed })
    }
    // All drafts exist before the first publication, so cycles cannot recurse forever.
    for (const record of records) {
      if (record.changed)
        record.entry = await client.request('PUT', record.path, { fields: record.fields }, record.entry?.sys.version)
      result.synced.push(record.note.id)
      if (!record.changed) result.unchanged.push(record.note.id)
      if (mode === 'preview') await writeState(record.note, 'preview')
    }
    if (mode === 'publish')
      for (const record of records) {
        const sys = record.entry.sys
        if (!sys.publishedVersion || sys.version !== sys.publishedVersion + 1)
          await client.request('PUT', `${record.path}/published`, undefined, sys.version)
        result.published.push(record.note.id)
        await writeState(record.note, 'published')
      }
    return result
  } catch (error) {
    error.result = result
    error.message += `; synced ${result.synced.length}, published ${result.published.length}/${plan.notes.length}. Rerun to resume.`
    throw error
  }
}

async function revalidate(config, result, fetcher = fetch) {
  if (!config.revalidateUrl || !result.published.length) return false
  const response = await fetcher(config.revalidateUrl, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'x-revalidate-secret': config.revalidateSecret },
    body: JSON.stringify({ contentTypeId: CONTENT_TYPE, noteIds: result.published }),
    signal: AbortSignal.timeout(30000)
  })
  if (!response.ok || (await response.json()).revalidated !== true)
    throw new Error(`Website refresh failed: HTTP ${response.status}`)
  return true
}

const running = (globalThis[Symbol.for('permanent-note-publisher.running')] ||= new WeakSet())
function createQuickAddModule(mode) {
  const names = {
    check: 'Permanent Check Current + Linked',
    preview: 'Permanent Preview Current + Linked',
    publish: 'Permanent Publish Current + Linked',
    all: 'Permanent Publish All'
  }
  if (!names[mode]) throw new Error('Invalid QuickAdd mode')
  const options = Object.fromEntries(
    Object.entries({
      spaceId: '',
      environmentId: 'master',
      managementToken: 'env:CONTENTFUL_MANAGEMENT_TOKEN',
      locale: 'en-US',
      cmaBaseUrl: 'https://api.contentful.com',
      revalidateUrl: '',
      revalidateSecret: ''
    }).map(([key, value]) => [
      key,
      {
        type: 'text',
        name: key,
        defaultValue: value,
        description: 'Supports env:VARIABLE_NAME. Permanent Note publishing only.'
      }
    ])
  )
  return {
    settings: { name: names[mode], author: 'Codex', options },
    entry: async ({ app, obsidian }, settings = {}) => {
      if (running.has(app)) throw new Error('A Permanent Note sync is already running')
      running.add(app)
      let result
      let config
      try {
        const roots =
          mode === 'all'
            ? app.vault.getMarkdownFiles().filter((f) => f.path.startsWith(ROOT))
            : [app.workspace.getActiveFile()]
        const plan = await buildPlan(app, obsidian.parseYaml, roots)
        if (!plan.notes.length) throw new Error('No Permanent notes found')
        if (mode === 'check') {
          new obsidian.Notice(
            `Checked ${plan.notes.length} cards\n${plan.notes.map((n) => n.title).join('\n')}\n${plan.warnings.join('\n')}`,
            15000
          )
          return plan
        }
        config = readSettings(settings)
        new obsidian.Notice(`Syncing ${plan.notes.length} Permanent cards, including linked cards…`, 8000)
        const writeState = async (note, state) => {
          const latest = (await app.vault.read(note.file)).replace(/^\uFEFF/, '').replace(/\r\n?/g, '\n')
          if (latest !== note.raw)
            throw new Error(`${note.file.path}: local note changed during sync; rerun with the latest content`)
          await app.fileManager.processFrontMatter(note.file, (fm) => {
            if (string(fm.id) !== note.id) throw new Error(`${note.file.path}: ID changed during sync`)
            Object.assign(fm, {
              contentful_content_type: CONTENT_TYPE,
              contentful_entry_id: entryId(note.id),
              contentful_note_id: note.id,
              contentful_locale: config.locale,
              contentful_last_mode: state,
              contentful_last_synced_at: new Date().toISOString()
            })
            if (state === 'published') fm.contentful_last_published_at = new Date().toISOString()
          })
        }
        result = await syncPlan(
          plan,
          createClient(config),
          config,
          mode === 'preview' ? 'preview' : 'publish',
          writeState
        )
        try {
          result.revalidated = await revalidate(config, result)
        } catch (error) {
          result.revalidateError = error.message
        }
        new obsidian.Notice(
          `${result.mode === 'publish' ? 'Published' : 'Synced drafts'}: ${plan.notes.length} cards\n${plan.warnings.join('\n')}${result.revalidateError ? '\n' + result.revalidateError : ''}`,
          15000
        )
        return result
      } catch (error) {
        // Partial publication is not atomic; refresh successful cards and report exact progress.
        if (config && error.result?.published.length) {
          try {
            await revalidate(config, error.result)
          } catch (refreshError) {
            error.message += `; ${refreshError.message}`
          }
        }
        new obsidian.Notice(`Permanent sync failed: ${error.message}`, 15000)
        throw error
      } finally {
        running.delete(app)
      }
    }
  }
}

module.exports = {
  CONTENT_TYPE,
  ROOT,
  parseNote,
  convertLinks,
  buildPlan,
  readSettings,
  createClient,
  assertSchema,
  syncPlan,
  revalidate,
  createQuickAddModule
}

module.exports = createQuickAddModule('preview')
